# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.ote_rate: debug

template:
  - sensor:
    - name: "Exchange rate EUR - CZK"
      unique_id: exchange_rate_eur_czk
      state: >
        {{ 24.57 }}

sensor:
  - platform: ote_rate