name: Build actions
on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/' custom_components/ote_rate/manifest.json
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/' custom_components/ote_rate/const.py
        
          cd custom_components/ote_rate/
          zip ../../ote_rate.zip ./* translations/* -x '.*'
      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./ote_rate.zip application/zip
